#!/usr/bin/env bash
echo > /tmp/trans_cache
while :
do
    sel=$(xsel --primary)
    cached=$(</tmp/trans_cache)
    if [ -n "$sel" ] && [ "$sel" != "$cached" ]
    then
        printf "\ec"
        echo "$sel" > /tmp/trans_cache
        /usr/local/bin/trans "$sel" $@
    fi
    sleep 0.3
done
